# cloudbuild.yaml
steps:
  # Este passo usa o builder padrão do Google (buildpacks) para construir sua aplicação Next.js
  - name: 'gcr.io/k8s-skaffold/pack'
    args:
      - 'build'
      - '--builder=gcr.io/buildpacks/builder:latest'
      # Injeta as variáveis de ambiente como argumentos de build.
      # Aqui é onde a mágica acontece para o Next.js!
      - '--env=NEXT_PUBLIC_FIREBASE_API_KEY=$_NEXT_PUBLIC_FIREBASE_API_KEY'
      - '--env=NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN'
      - '--env=NEXT_PUBLIC_FIREBASE_PROJECT_ID=$_NEXT_PUBLIC_FIREBASE_PROJECT_ID'
      - '--env=NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET'
      - '--env=NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID'
      - '--env=NEXT_PUBLIC_FIREBASE_APP_ID=$_NEXT_PUBLIC_FIREBASE_APP_ID'
      - '--image=us-east4-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME:$COMMIT_SHA'
      - '--publish'
# Esta seção é onde você pode declarar as variáveis.
# É opcional se você for passar todas pela linha de comando.
substitutions:
  _NEXT_PUBLIC_FIREBASE_API_KEY: ""
  # ... (declare as demais se quiser)
# Esta opção é crucial! Ela permite que as variáveis de substituição
# sejam automaticamente mapeadas como variáveis de ambiente em todos os passos do build.
options:
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY